version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
      - "192.168.15.90:3000:3000"
      - "10.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://10.0.0.1:8000
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
      - "192.168.15.90:8000:8000"
      - "10.0.0.1:8000:8000"
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=zoologicdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
      - "192.168.15.90:3306:3306"
      - "10.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zoologicdb
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 